### ISSUE TITLE
Q&A Logic: More Answered Questions

### ISSUE THREAD

**Issue by AnswerAye** [RFCE2209Targaryen/FEC#94]
Clicking more answered questions over and over again eventually makes the button disappear instead of changing to collapse questions.

https://github.com/RFCE2209Targaryen/FEC/blob/main/client/src/components/questionsComponent/Question.jsx#L68-L88

Task 1: Create a seperate state to keep track of what is rendered on the button.
Task 2: In your adjust Question viewcount length, if you are at the end of your array, change the button render state to 'Collapse Questions'
Task 3: Pass this state to your button
Task 4: If the button is clicked while the current button state is 'Collapse Questions' have it just render the first 4 entries like normal.

**Comment by CameronMontgomery** [comment]
Per the business requirements the button is to disappear, not change 

**From FEC Business requirements** 
More Answered Questions
The list will by default only display up to 2 questions asked. If there are more than 2 questions that have been asked for the given product, a button for “More Answered Questions” will appear below the list. 
If there are 2 or less questions for the given product, then the button will not appear.

Clicking this button will cause up to 2 additional questions to appear. The list should expand, and the questions should show in order below the previously loaded questions.

As long as there are still unloaded questions, the button will remain below the list. Once all of the questions for the product have been loaded, the button should no longer appear.
